"""vendas att

Revision ID: c8a7ee6ef5be
Revises: cd953af3d22f
Create Date: 2025-08-27 18:18:18.449118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8a7ee6ef5be'
down_revision = 'cd953af3d22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
